version: '2'
services:
    writ-web:
        image: divanvisagie/writ-web
        ports:
            - "8000:80"
        links:
            - writapi:writapi
        depends_on:
            - writapi
    writapi:
        image: divanvisagie/writ-api:latest
        ports:
          - "9999:9999"
          - "9990:9990"
        links:
          - swissguard:swissguard
        depends_on:
          - swissguard
    swissguard:
        image: divanvisagie/swissguard:latest
        ports:
            - "8888:9999"
            - "8880:9990"
